[game]
<<<<<<< Updated upstream:Resources/ConfigPresets/_Mono/citadelInferno.toml
hostname = "[EN][MRP] Citadel | Inferno [EU West]"
=======
hostname = "[EN][MRP] Derelict | Rift [NA East]"
>>>>>>> Stashed changes:Resources/ConfigPresets/_Mono/derelictRift.toml
desc = "A player-centric, ship-based, combat fork with a minimal ruleset. Featuring bluespace drives, ship artillery, autoloaders, shields, collisions, custom ships, companies, and original lore. Be sure to join our Discord!"
